---
- name: Install cert-manager into the cluster
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  become: true
  tasks:
    - name: Ensure the helm repo for cert-manager is added
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"
    - name: Ensure the cert-manager CRD configuration has been applied
      kubernetes.core.k8s:
        state: present
        src: https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.crds.yaml
    - name: Ensure the cluster CA is configured
      kubernetes.core.k8s:
        state: present
        template: ca.yml.j2
    - name: Ensure the cert-manager helm chart is installed
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        wait: true
- name: Install cert-manager CLI on the first control plane node
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  become: true
  tasks:
    - name: Ensure Go is installed
      ansible.builtin.apt:
        name: golang
    - name: Ensure the certmanager CLI is installed
      ansible.builtin.uri:
        url: https://github.com/cert-manager/cmctl/releases/latest/download/cmctl_linux_amd64
        dest: /usr/local/bin/cmctl
        creates: /usr/local/bin/cmctl
        owner: root
        group: root
        mode: '0755'

