---
# This top level playbook is only for including smaller playbooks which can be
# developed and tested separately before adding them here.  The included
# playbooks can (and do) use "${{ tf_workspace }}.vars.yml" as a vars-file so
# that you can have different variable files for each workspace allowing you
# to use the same playbooks for multiple projects.  When you run the
# ansible-playbook command, be sure to use the -e option to pass a value for
# tf_workspace.
#
# example:
# ansible-playbook -e tf_workspace=$(tofu workspace show) ansible/playbook.yml
#
- import_playbook: playbook-k3s-node-baseline.yml
- import_playbook: playbook-k3s-first-control-plane.yml
- import_playbook: playbook-k3s-additional-control-planes.yml
- import_playbook: playbook-k3s-workers.yml
- import_playbook: playbook-k3s-completion.yml
- import_playbook: playbook-update-local-kubeconfig.yml
- import_playbook: playbook-nfs.yml
- import_playbook: playbook-prometheus.yml

# Optional apps (uncomment the ones you want)

#- import_playbook: playbook-certmanager.yml
#- import_playbook: playbook-longhorn.yml
#- import_playbook: playbook-gitea.yml
- import_playbook: playbook-cnpg.yml
- import_playbook: playbook-immich.yml
- import_playbook: playbook-jellyfin.yml
- import_playbook: playbook-firefly-iii.yml
- import_playbook: playbook-wger.yml
