---
- name: Install immich into the cluster
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  become: true
  tasks:
    - name: Ensure the immich namespace exists
      kubernetes.core.k8s:
        name: immich
        api_version: v1
        kind: Namespace
        state: present
    - name: Ensure immich credentials for cnpg exist
      kubernetes.core.k8s:
        state: present
        template: secret-immich-postgres-credentials.yml.j2
    - name: Ensure immich credentials for minio exist
      kubernetes.core.k8s:
        state: present
        template: secret-immich-minio-credentials.yml.j2
    - name: Ensure a cnpg database exists for immich (takes a while - waiting up to 10 min.)
      kubernetes.core.k8s:
        state: present
        template: cnpg-immich-cluster.yml.j2
        wait: yes
        wait_timeout: 600
        wait_condition:
          type: Ready
          status: "True"
          reason: ClusterIsReady
    - name: Ensure the helm repo for immich is added
      kubernetes.core.helm_repository:
        name: immich
        repo_url: "https://immich-app.github.io/immich-charts"
    - name: Ensure the immich PVC configuration has been applied
      kubernetes.core.k8s:
        state: present
        template: immich-library-pvc.yml.j2
    - name: Ensure the immich helm chart is installed
      kubernetes.core.helm:
        name: immich
        chart_ref: immich/immich
        release_namespace: immich
        create_namespace: true
        wait: true
        values: "{{ lookup('template', 'helm-values-immich.yml.j2', variable_start_string='{{{', variable_end_string='}}}') | from_yaml }}"
    - name: Ensure the immich ingress configuration has been applied
      kubernetes.core.k8s:
        state: present
        template: traefik-ingress-immich.yml.j2
    - name: Ensure scheduled backups for the database are configured and initial backup performed
      kubernetes.core.k8s:
        state: present
        template: cnpg-immich-cluster-backup.yml.j2
        wait: yes
        wait_timeout: 600
        # wait_condition:
        #   type: LastBackupSucceeded
        #   status: "True"
        #   reason: LastBackupSucceeded
