---
- name: Install Longhorn into the cluster
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  become: true
  tasks:
    - name: Ensure the helm repo for longhorn is added
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"
    - name: Ensure the longhorn helm chart is installed
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        values:
          defaultSettings:
            defaultDataPath: /k3s_storage
            backupTarget: nfs://truenas1.site1.thebrownleefamily.net:/mnt/pool1/longhorn-backups
          ingress:
            enabled: true
            ingressClassName: traefik
            host: "{{ cnames.longhorn }}"
            path: /
