---
- name: Install cnpg (Cloud Native PostgreSQL) into the cluster
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  tasks:
    - name: Ensure the helm repo for cnpg is added
      kubernetes.core.helm_repository:
        name: cnpg
        repo_url: "https://cloudnative-pg.github.io/charts"
    - name: Ensure the cnpg helm chart is installed
      kubernetes.core.helm:
        name: cnpg
        chart_ref: cnpg/cloudnative-pg
        release_namespace: cnpg-system
        create_namespace: true
        wait: true
        values:
          image:
            tag: latest
          config:
            clusterWide: true
    - name: Ensure the cnpg deployment is ready before continuing
      ansible.builtin.command:
        cmd: "kubectl wait -n cnpg-system --for=condition=Available deployment --selector app.kubernetes.io/name=cloudnative-pg"
      changed_when: false
    - name: Ensure the cnpg plugin for kubectl is installed
      ansible.builtin.apt:
        deb: "{{ cnpg_kubectl_plugin_url }}"
    - name: Ensure /root/.bashrc.d/cnpg-kubectl.rc exists
      ansible.builtin.template:
        dest: /root/.bashrc.d/cnpg-kubectl.rc
        src: cnpg-kubectl.rc.j2
        owner: root
        group: root
        mode: '0600'
