---
- name: Configure kubectl alias and completion for root
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  become: true
  tasks:
    - name: Ensure /root/.bashrc.d/kubernetes.rc exists
      ansible.builtin.template:
        dest: /root/.bashrc.d/kubernetes.rc
        src: kubernetes.rc.j2
        owner: root
        group: root
        mode: '0600'
