---
- name: Install firefly into the cluster
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  become: true
  tasks:
    - name: Ensure the firefly namespace exists
      kubernetes.core.k8s:
        name: firefly
        api_version: v1
        kind: Namespace
        state: present
    - name: Ensure credentials for the firefly database exist
      kubernetes.core.k8s:
        state: present
        template: secret-firefly-postgres-credentials.yml.j2
    - name: Ensure a cnpg database exists for firefly (takes a while - waiting up to 10 min.)
      kubernetes.core.k8s:
        state: present
        template: cnpg-firefly-cluster.yml.j2
        wait: yes
        wait_timeout: 600
        wait_condition:
          type: Ready
          status: "True"
          reason: ClusterIsReady
    - name: Ensure the helm repo for firefly is added
      kubernetes.core.helm_repository:
        name: firefly-iii
        repo_url: "https://firefly-iii.github.io/kubernetes/"
    - name: Ensure the firefly PVC configuration has been applied
      kubernetes.core.k8s:
        state: present
        template: pvc-firefly-attachments.yml.j2
    - name: Ensure the firefly helm chart is installed
      kubernetes.core.helm:
        name: firefly-iii
        chart_ref: firefly-iii/firefly-iii
        release_namespace: firefly
        create_namespace: true
        wait: true
        values: "{{ lookup('template', 'helm-values-firefly.yml.j2') | from_yaml }}"
    - name: Ensure the firefly importer helm chart is installed
      kubernetes.core.helm:
        name: firefly-iii-importer
        chart_ref: firefly-iii/importer
        release_namespace: firefly
        create_namespace: false
        wait: true
        values: "{{ lookup('template', 'helm-values-firefly-importer.yml.j2') | from_yaml }}"
    - name: Ensure the firefly ingress configuration has been applied
      kubernetes.core.k8s:
        state: present
        template: traefik-ingress-firefly.yml.j2
    - name: Ensure the firefly importer ingress configuration has been applied
      kubernetes.core.k8s:
        state: present
        template: traefik-ingress-importer.yml.j2
