- name: Update local kubeconfig
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  tasks:
    - name: Ensure local directory for kubeconfig exists
      ansible.builtin.file:
        path: "../.kube"
        state: directory
        mode: '0700'
      delegate_to: localhost
    - name: Fetching kubeconfig
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "../.kube/{{ k3s_vip_hostname }}.kubeconfig"
        flat: yes
        mode: '0600'
      become: yes
    - name: Ensure kubeconfig uses VIP endpoint
      ansible.builtin.shell:
        cmd: /usr/bin/yq -i '.clusters[0].name = "{{ k3s_vip_hostname }}" |.clusters[0].cluster.server = "https://{{ k3s_vip_hostname }}.{{ ansible_domain }}:6443" | .contexts[0].context.cluster = "{{ k3s_vip_hostname }}"' ../.kube/{{ k3s_vip_hostname }}.kubeconfig
      delegate_to: localhost
