---
- name: Common
  hosts: all
  environment:
    INSTALL_K3S_SKIP_START: true
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    K3S_TOKEN: "{{ k3s_token }}"
  tasks:
    - name: Ensure common packages are installed
      ansible.builtin.apt:
        name:
          - python3-kubernetes
          - ipvsadm
        lock_timeout: 180
      become: true
    - name: Ensure the K3S drop-in configuration directory exists
      ansible.builtin.file:
        path: /etc/rancher/k3s/config.yaml.d
        state: directory
        owner: root
        group: root
        mode: '0755'
      become: true
    - name: Include role-specific tasks
      ansible.builtin.include_tasks:
        file: tasks-{{ k3s_role }}.yml
