---
- name: Install cnpg (Cloud Native PostgreSQL) into the cluster
  hosts: k3s_first_control_plane
  vars_files:
    - "{{ tf_workspace }}.vars.yml"
  become: true
  tasks:
    - name: Ensure the helm repo for cnpg is added
      kubernetes.core.helm_repository:
        name: cnpg
        repo_url: "https://cloudnative-pg.github.io/charts"
    - name: Ensure the cnpg namespace exists
      kubernetes.core.k8s:
        name: cnpg
        api_version: v1
        kind: Namespace
        state: present
    - name: Ensure the cnpg helm chart is installed
      kubernetes.core.helm:
        name: cnpg
        chart_ref: cnpg/cloudnative-pg
        release_namespace: cnpg
        create_namespace: true
        values:
          config:
            clusterWide: false
    - name: Ensure the cnpg deployment is ready before continuing
      ansible.builtin.command:
        cmd: "kubectl wait -n cnpg --for=condition=Available deployment --selector app.kubernetes.io/name=cloudnative-pg"
      changed_when: false
