apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: immich
spec: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
