apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: immich
spec: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photos
  namespace: immich
spec:
  ingressClassName: traefik
  rules:
  - host: photos.site1.thebrownleefamily.net
    http:
      paths:
      - backend:
          service:
            name: immich-server
            port:
              number: 3001
        path: /
        pathType: Prefix
