---
- name: Install Longhorn into the cluster
  hosts: localhost
  vars_files:
    - cnames.yaml
  tasks:
    - name: Ensure the helm repo for longhorn is added
      kubernetes.core.helm_repository:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: longhorn
        repo_url: "https://charts.longhorn.io"
    - name: Ensure the longhorn helm chart is installed
      kubernetes.core.helm:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
    - name: Ensure the longhorn ingress configuration has been applied
      kubernetes.core.k8s:
        kubeconfig: "{{ k3s_local_kubeconfig_path }}"
        state: present
        template: longhorn-ingress.yaml
