---
- name: Prepare DNS virtual machines
  hosts: all
  become: yes
  tasks:
    - name: Wait until the lock file is removed
      ansible.builtin.wait_for:
        path: /var/lock/file.lock
        state: absent
    - name: Ensure package cache is updated
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Ensure common packages are installed
      ansible.builtin.apt:
        name:
          - bash-completion
          - ca-certificates
          - curl
          - vim
    - name: Ensure role specific packages are installed
      ansible.builtin.apt:
        name:
          - bind9
          - bind9-dnsutils
    - name: Ensure named is configured to include the local zone files
      ansible.builtin.template:
        dest: /etc/bind/named.conf.local
        owner: root
        group: root
        mode: '0644'
        src: named.conf.local.j2
      register: local_zone_config
    - name: Ensure the local zone files are copied
      ansible.builtin.copy:
        dest: /etc/bind/
        owner: root
        group: root
        mode: '0644'
        src: files/dns-zone-files/
      register: local_zone_db_files
    - name: Ensure named is reloaded if the zone files changed
      ansible.builtin.systemd:
        name: named
        state: restarted
      when: local_zone_config.changed or local_zone_db_files.changed
    - name: Ensure systemd-resolved is disabled
      ansible.builtin.systemd:
        name: systemd-resolved
        state: stopped
        enabled: false
